apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-sample
    app.kubernetes.io/part-of: my-application
  name: go-sample
  namespace: vnambiar-hac
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: go-sample
status:
  loadBalancer: {}
